### ISSUE TITLE
Wrong Command Line parsing for add / messages

### ISSUE THREAD

**Issue by lombad** [codecovevienna/gittt-cli#20]
```
xxx@UUUU a-project [master] % gittt add -y 2019 -m 5 -d 14 -h 14 -M 00 -w "swagger research" -a 1 -t Time   

> @xxx/yyyy@1.0.4 start /xxx/gittt-cli
> ts-node index.ts "add" "-y" "2019" "-m" "5" "-d" "14" "-h" "14" "-M" "00" "-w" "swagger" "research" "-a" "1" "-t" "Time"

No amount option found
(node:4363) UnhandledPromiseRejectionWarning: TypeError: cmd.help is not a function
    at App.<anonymous> (/xxx/gittt-cli/app.ts:584:20)
    at Generator.next (<anonymous>)
    at /xxx/gittt-cli/app.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/xxx/gittt-cli/app.ts:3:12)
    at App.addAction (/xxx/gittt-cli/app.ts:485:16)
    at App.<anonymous> (/xxx/gittt-cli/app.ts:673:20)
    at Generator.next (<anonymous>)
    at /xxx/gittt-cli/app.ts:7:71
    at new Promise (<anonymous>)
(node:4363) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4363) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by lombad** [comment]
You can use -w "swagger_reasearch" instead

**Comment by eiabea** [comment]
Moved to JIRA
